name: Deploy S3 Bucket

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: us-east-1

      - name: Validate CloudFormation template
        run: |
          echo "Validando template..."
          aws cloudformation validate-template \
            --template-body file://main.yaml

      - name: Deploy CloudFormation stack
        run: |
          STACK_NAME=MiBucketS3Stack
          TEMPLATE_FILE=main.yaml

          echo "Desplegando stack $STACK_NAME..."
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file $TEMPLATE_FILE \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset \
            --region us-east-1

      - name: Show Stack Outputs
        run: |
          STACK_NAME=MiBucketS3Stack
          echo "Outputs del stack:"
          aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --query "Stacks[0].Outputs" \
            --output table
